[alias]
# Aliases with dynamic linking enabled
checkd = "check --features bevy/dynamic_linking"
buildd = "build --features bevy/dynamic_linking"
rund = "run --features bevy/dynamic_linking"
testd = "test --features bevy/dynamic_linking"
clippyd = "clippy --features bevy/dynamic_linking"

# Aliases for wasm
checkw = "check --target wasm32-unknown-unknown"
buildw = "build --target wasm32-unknown-unknown"
runw = "run --target wasm32-unknown-unknown"
# testw = "test --target wasm32-unknown-unknown"
clippyw = "clippy --target wasm32-unknown-unknown"

[target.'cfg(target_family = "wasm")']
runner = "wasm-server-runner"
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]
